name: Pull Request Test

on:
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4.1.7

      - name: JDK 설치
        uses: actions/setup-java@v4.3.0
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Gradle Build
        run: |
          ./gradlew build --parallel
